### ISSUE TITLE
PickleAdapter 사진 선택 버그

### ISSUE THREAD

**Issue by kklyoon** [sabujak-sabujak/Pickle#14]
PickleFragment 에서 사진 선택시 버그가 발생합니다.
Selection 을 다시 구현하신다고 하셨는데 구현시 참고하시기 바랍니다.

* 재현방법: 사진을 선택하고 스크롤을 얼마간 내린 후 다시 올려서 사진이 선택된게 맞는지 확인한다.
* 기대동작: 선택된 사진이 선택된 걸로 나옴
* 실제동작: 선택된 사진이 선택이 안된걸로 나옴

**Comment by Charlezz** [comment]
selection의존성을 제거했습니다.
